service: Slack-App

package:
  artifact: handler.zip

provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}  
  role: ${self:custom.roles.${self:provider.stage}}
  profile: ${self:custom.profiles.${self:provider.stage}}
  runtime: python2.7
  region: us-east-1
  memorySize: 512
  deploymentBucket:
    serverSideEncryption: AES256 # Enable encryption on S3 bucket
  versionFunctions: false

custom:
  defaultStage: dev
  profiles:
    dev: "dev_profile"
    prod: "prod_profile"
  roles:
    dev: "dev_role"
    prod: "prod_role"    

functions:
  login:
    handler: handler.Handle
    tags:
      name: value
    events:
      - http:
          path: slack
          description: "Executes Slack commands against Urban Dictionary"
          method: post
          cors: true
